# Generated by Django 3.2.5 on 2021-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='langauage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('symbol', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='project/default.png', null=True, upload_to='projects/')),
                ('title', models.CharField(max_length=250)),
                ('short_desc', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('symbol', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('fullname', models.CharField(max_length=250)),
                ('short_bio', models.TextField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('github', models.CharField(help_text='Github username', max_length=200)),
                ('lang', models.ManyToManyField(to='developer.langauage')),
                ('projects', models.ManyToManyField(help_text='project', to='developer.project')),
                ('tools', models.ManyToManyField(to='developer.tool')),
            ],
        ),
    ]
