# Generated by Django 3.2.5 on 2021-08-13 19:17

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to=blog.models.upload_location)),
                ('title', models.CharField(help_text='Blog title', max_length=250, unique=True)),
                ('body', models.TextField()),
                ('youtube_src', models.CharField(blank=True, default='', max_length=200)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('author', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.tag')),
            ],
            options={
                'verbose_name_plural': 'Blog Entry.',
                'ordering': ['-pub_date', '-id'],
            },
        ),
    ]
