# Generated by Django 3.2.5 on 2021-08-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/')),
                ('title', models.CharField(help_text='Blog title', max_length=250, unique=True)),
                ('body', models.TextField()),
                ('youtube_src', models.URLField(blank=True, default='')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('tag', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.tag')),
            ],
            options={
                'verbose_name_plural': 'Blog Entry.',
                'ordering': ['-pub_date', 'id'],
            },
        ),
    ]
